const WHATSAPP_NUMBER = '33603939226';
const INSTAGRAM_URL = 'https://instagram.com/locabey.official';
const EMAIL = 'contact@locabey.com';

function toggleContact(){document.querySelector('.contact-wrap')?.classList.toggle('open');document.querySelector('.nav')?.classList.remove('mobile-open')}
function toggleMobileNav(e){e?.stopPropagation();document.querySelector('.nav')?.classList.toggle('mobile-open');document.querySelector('.contact-wrap')?.classList.remove('open')}
document.addEventListener('click',e=>{const w=document.querySelector('.contact-wrap');if(w&&!w.contains(e.target))w.classList.remove('open');const n=document.querySelector('.nav');if(n&&!n.contains(e.target))n.classList.remove('mobile-open')})

function getStoredCart(){try{return JSON.parse(localStorage.getItem('locabeyCart')||'[]')}catch{return[]}}
function setStoredCart(cart){localStorage.setItem('locabeyCart',JSON.stringify(cart));updateCartCount()}
function navCartClick(e){if(window.innerWidth<=760){e.preventDefault();openSheet()}}
function updateCartCount(){const cart=getStoredCart();document.querySelectorAll('[data-cart-count]').forEach(el=>el.textContent=cart.length||'');const tot=cart.length?cartTotalText(cart):'';document.querySelectorAll('[data-cart-total]').forEach(el=>el.textContent=tot)}
function openWhatsAppMessage(message){window.open(`https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(message)}`,'_blank')}
function openInstagram(){window.open(INSTAGRAM_URL,'_blank')}
function openEmail(subject='LocaBey request',body='Hi LocaBey, I would like to discuss a project.'){window.location.href=`mailto:${EMAIL}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`}
function nav(){return `
<nav class="nav"><div class="wrap nav-inner"><a class="brand" href="index.html"><div class="logo">LB</div>LocaBey</a><div class="links"><a href="index.html">Home</a><a href="social-growth.html">Social Growth</a><a href="agency.html">Agency Services</a></div><div class="nav-actions"><button class="btn ghost mobile-menu-btn" onclick="toggleMobileNav(event)">Menu</button><a class="btn ghost nav-cart-btn" href="cart.html" onclick="navCartClick(event)">🛒<span class="cart-label"> Cart </span><span class="cart-count" data-cart-count></span><span class="cart-nav-total" data-cart-total></span></a><div class="contact-wrap"><button class="btn white" onclick="toggleContact()">Contact</button><div class="contact-menu"><a href="javascript:void(0)" onclick="openWhatsAppMessage('Hi LocaBey, I need help choosing the right service.')">WhatsApp</a><a href="javascript:void(0)" onclick="openInstagram()">Instagram DM</a><a href="javascript:void(0)" onclick="openEmail()">Email</a></div></div></div></div></nav>`}
function footer(){return`<footer><div class="wrap footer-inner"><strong class="footer-name">LocaBey</strong><span class="footer-tagline">Your business builder, one-stop shop.</span><span class="footer-copy">© 2026 LocaBey · Paris</span></div></footer>`}
function cartSheetHTML(){return`<div class="sheet-bg" id="sheetBg" onclick="closeSheet()"></div><div class="cart-sheet" id="cartSheet"><div class="sheet-handle"></div><div class="sheet-header"><h3>Your Cart</h3><button class="sheet-close" onclick="closeSheet()">×</button></div><div class="sheet-items" id="sheetItems"></div><div class="sheet-footer"><div class="sheet-total-row"><span>Total</span><strong id="sheetTotal">0€</strong></div><p class="note sheet-note">No password needed. Confirmed before payment.</p><button class="btn green" style="width:100%;margin-top:12px;min-height:48px" onclick="openWhatsApp();closeSheet()">Send order on WhatsApp ↗</button><button class="btn muted-btn" style="width:100%;margin-top:8px;min-height:42px" onclick="clearCart()">Clear cart</button></div></div>`}
function injectShell(){document.body.insertAdjacentHTML('afterbegin',nav());document.body.insertAdjacentHTML('beforeend',footer());if(!document.getElementById('cartSheet'))document.body.insertAdjacentHTML('beforeend',cartSheetHTML());updateCartCount()}

const serviceIcons={Followers:'👥',Subscribers:'👥','Channel Members':'👥',Likes:'❤️','Post Likes':'❤️','Page Likes':'👍',Comments:'💬',Reactions:'💬',Views:'👁','Channel Views':'👁','Post Views':'👁','Clip Views':'👁','Live Viewers':'👁',Saves:'🔖',Shares:'➤',Reposts:'🔁',Favorites:'⭐',Plays:'▶',Subscriptions:'🔔','Profile Views':'👤','Watch Hours':'⏱','Monthly Listeners':'🎧','Playlist Adds':'➕'};
const platLogos={Instagram:'instagram',TikTok:'tiktok',YouTube:'youtube',Facebook:'facebook','X / Twitter':'twitter',Spotify:'spotify',Snapchat:'snapchat',Twitch:'twitch',Telegram:'telegram'};
function platLogo(p){return`logos/${platLogos[p]||p.toLowerCase()}.svg`}
const catalog={
Instagram:{icon:'<img src="logos/instagram.svg" class="plat-logo" alt="">',services:{Followers:{'100':5,'500':10,'1,000':15,'5,000':40,'10,000':75,Custom:'Custom'},Likes:{'100':3,'500':7,'1,000':10,'5,000':35,'10,000':60,Custom:'Custom'},Views:{'100':1,'500':3,'1,000':5,'5,000':15,'10,000':25,Custom:'Custom'},Comments:{'100':10,'500':30,'1,000':50,Custom:'Custom'},Saves:{'100':5,'500':12,'1,000':20,'5,000':60,Custom:'Custom'},Shares:{'100':2,'500':5,'1,000':9,'5,000':20,Custom:'Custom'}}},
TikTok:{icon:'<img src="logos/tiktok.svg" class="plat-logo" alt="">',services:{Followers:{'100':5,'500':15,'1,000':25,'5,000':60,'10,000':100,Custom:'Custom'},Likes:{'100':3,'500':7,'1,000':15,'5,000':35,'10,000':70,Custom:'Custom'},Views:{'100':1,'500':3,'1,000':5,'5,000':15,'10,000':25,Custom:'Custom'},Comments:{'100':10,'500':25,'1,000':45,Custom:'Custom'},Reposts:{'100':5,'500':15,'1,000':25,Custom:'Custom'},Favorites:{'100':5,'500':15,'1,000':25,Custom:'Custom'}}},
YouTube:{icon:'<img src="logos/youtube.svg" class="plat-logo" alt="">',services:{Subscribers:{'100':10,'500':40,'1,000':70,'5,000':200,Custom:'Custom'},Views:{'100':2,'500':5,'1,000':10,'5,000':25,'10,000':45,Custom:'Custom'},'Watch Hours':{'100h':20,'500h':60,'1,000h':100,'4,000h':300,Custom:'Custom'},Likes:{'100':5,'500':10,'1,000':20,Custom:'Custom'}}},
Facebook:{icon:'<img src="logos/facebook.svg" class="plat-logo" alt="">',services:{'Page Likes':{'100':2,'500':10,'1,000':15,'5,000':60,'10,000':100,Custom:'Custom'},Followers:{'100':3,'500':15,'1,000':20,'5,000':75,Custom:'Custom'},'Post Likes':{'100':1,'500':5,'1,000':10,'5,000':40,Custom:'Custom'}}},
'X / Twitter':{icon:'<img src="logos/twitter.svg" class="plat-logo" alt="">',services:{Followers:{'100':15,'500':75,'1,000':150,'5,000':500,Custom:'Custom'},Likes:{'100':10,'500':50,'1,000':100,'5,000':400,Custom:'Custom'},Reposts:{Custom:'Custom'},Views:{Custom:'Custom'}}},
Spotify:{icon:'<img src="logos/spotify.svg" class="plat-logo" alt="">',services:{Plays:{'100':2,'500':5,'1,000':10,'5,000':25,'10,000':45,Custom:'Custom'},Followers:{'100':7,'500':15,'1,000':25,'5,000':70,Custom:'Custom'},'Monthly Listeners':{'100':10,'500':20,'1,000':40,'5,000':100,Custom:'Custom'},'Playlist Adds':{'100':8,'500':18,'1,000':35,Custom:'Custom'}}},
Snapchat:{icon:'<img src="logos/snapchat.svg" class="plat-logo" alt="">',services:{Followers:{Custom:'Custom'},Shares:{Custom:'Custom'},Subscriptions:{Custom:'Custom'},'Profile Views':{Custom:'Custom'}}},Twitch:{icon:'<img src="logos/twitch.svg" class="plat-logo" alt="">',services:{Followers:{Custom:'Custom'},'Channel Views':{Custom:'Custom'},'Live Viewers':{Custom:'Custom'},'Clip Views':{Custom:'Custom'}}},Telegram:{icon:'<img src="logos/telegram.svg" class="plat-logo" alt="">',services:{'Channel Members':{Custom:'Custom'},'Post Views':{Custom:'Custom'},Reactions:{Custom:'Custom'},Comments:{Custom:'Custom'}}}
};
const bundleMap={Instagram:['Likes','Views','Saves','Shares'],TikTok:['Likes','Views','Reposts','Favorites'],YouTube:['Views','Likes','Watch Hours','Subscribers'],Facebook:['Post Likes','Followers','Page Likes'],'X / Twitter':['Likes','Reposts','Views'],Spotify:['Plays','Monthly Listeners','Playlist Adds'],Snapchat:['Shares','Profile Views'],Twitch:['Channel Views','Clip Views','Live Viewers'],Telegram:['Post Views','Reactions','Comments']};
let selectedPlatform='Instagram',selectedService='Followers',selectedQuantity='1,000',selectedDelivery='Immediate 24h',customMode=false;
function euro(v){return typeof v==='number'?v+'€':v}function priceObject(){return catalog[selectedPlatform].services[selectedService]}function getPrice(){if(customMode)return'Custom';return priceObject()[selectedQuantity]??'Custom'}
function perUnit(price,qty){if(typeof price!=='number')return'';const n=parseInt(String(qty).replace(/,/g,'').replace('h',''));if(!n||String(qty).includes('h'))return'';return(price/(n/1000)).toFixed(1).replace('.0','')+'€ / 1K'}
function badge(q,p){if(typeof p!=='number')return'';const n=parseInt(String(q).replace(/,/g,''));if(n>=5000)return'<span class="badge">Best value</span>';if(n>=1000)return'<span class="badge">Popular</span>';return''}
function initBuilder(){if(!document.getElementById('platformTiles'))return;window.platformTiles=document.getElementById('platformTiles');window.serviceTiles=document.getElementById('serviceTiles');window.quantityGrid=document.getElementById('quantityGrid');window.customQty=document.getElementById('customQty');window.urlEl=document.getElementById('url');window.bundleEl=document.getElementById('bundle');window.bundleOptionsEl=document.getElementById('bundleOptions');window.cartItemsEl=document.getElementById('cartItems');window.cartTotalEl=document.getElementById('cartTotal');urlEl.addEventListener('input',updateSummary);const deliveryCustomInput=document.getElementById('deliveryCustomInput');if(deliveryCustomInput)deliveryCustomInput.addEventListener('input',updateSummary);customQty.addEventListener('input',()=>{selectQuantity('Custom');});renderAll();renderMiniCart()}
function renderPlatforms(){platformTiles.innerHTML=Object.keys(catalog).map(p=>`<div class="tile ${p===selectedPlatform?'active':''}" onclick="selectPlatform('${p.replace(/'/g,"\\'")}')"><span class="icon">${catalog[p].icon}</span><strong>${p}</strong></div>`).join('')}
function renderServices(){const services=Object.keys(catalog[selectedPlatform].services);if(!services.includes(selectedService))selectedService=services[0];serviceTiles.innerHTML=services.map(s=>`<div class="service-tile ${s===selectedService?'active':''}" onclick="selectService('${s.replace(/'/g,"\\'")}')"><span class="s-icon">${serviceIcons[s]||''}</span><strong>${s}</strong></div>`).join('')}
function renderQuantities(){const prices=priceObject();if(!prices[selectedQuantity])selectedQuantity=Object.keys(prices)[0];document.getElementById('priceGuideTitle').textContent=`${selectedPlatform} ${selectedService} pricing`;quantityGrid.innerHTML=Object.entries(prices).filter(([q])=>q!=='Custom').map(([q,p])=>`<div class="qty-tile ${!customMode&&q===selectedQuantity?'active':''}" onclick="selectQuantity('${q}')"><strong>${q}</strong><span class="price">${euro(p)}</span><span class="per">${perUnit(p,q)}</span>${badge(q,p)}</div>`).join('');if(prices.Custom){quantityGrid.innerHTML+=`<div class="qty-tile ${customMode?'active':''}" onclick="selectQuantity('Custom')"><strong>Custom</strong></div>`}const customQtyRow=document.getElementById('customQtyRow');if(customQtyRow)customQtyRow.style.display=customMode?'block':'none';updateSummary()}
function selectPlatform(p){selectedPlatform=p;selectedService=Object.keys(catalog[p].services)[0];selectedQuantity=Object.keys(catalog[p].services[selectedService])[0];customMode=false;renderAll()}function selectService(s){selectedService=s;selectedQuantity=Object.keys(catalog[selectedPlatform].services[s])[0];customMode=false;renderAll()}function selectQuantity(q){if(q==='Custom'){customMode=true;selectedQuantity=customQty.value?customQty.value+' custom':'Custom'}else{customMode=false;selectedQuantity=q}renderQuantities()}function selectDelivery(d,el){selectedDelivery=d;document.querySelectorAll('.delivery-tile').forEach(t=>t.classList.remove('active'));el.classList.add('active');const row=document.getElementById('deliveryCustomRow');if(row)row.style.display=d==='Custom'?'block':'none';updateSummary()}function dismissBundle(){if(window.bundleEl)bundleEl.classList.remove('show')}
function getCurrent(){const deliveryCustomEl=document.getElementById('deliveryCustomInput');const delivery=selectedDelivery==='Custom'&&deliveryCustomEl?.value.trim()?'Custom: '+deliveryCustomEl.value.trim():selectedDelivery;return{type:'social-growth',platform:selectedPlatform,service:selectedService,quantity:selectedQuantity,delivery,url:urlEl?.value.trim()||'',price:getPrice()}}
function updateSummary(){if(!document.getElementById('sumPlatform'))return;const i=getCurrent();sumPlatform.textContent=i.platform;sumService.textContent=i.service;sumQuantity.textContent=i.quantity;sumDelivery.textContent=i.delivery;sumUrl.textContent=i.url?'Added':'Missing';sumPrice.textContent=euro(i.price);}
function addToCart(){const cart=getStoredCart();cart.push(getCurrent());setStoredCart(cart);renderMiniCart();showBundle(selectedPlatform,selectedService);const bar=document.getElementById('cartBar');if(bar){bar.classList.add('flash');setTimeout(()=>bar.classList.remove('flash'),550)}}function showBundle(p,current){const sug=(bundleMap[p]||[]).filter(s=>s!==current&&catalog[p].services[s]);bundleOptionsEl.innerHTML=sug.map(s=>`<span class="pill" onclick="prefillAddon('${p}','${s}')">Add ${p} ${s}</span>`).join('');bundleEl.classList.add('show')}function prefillAddon(p,s){selectedPlatform=p;selectedService=s;selectedQuantity=Object.keys(catalog[p].services[s])[0];customMode=false;urlEl.value=getStoredCart().at(-1)?.url||urlEl.value;renderAll();document.getElementById('builder').scrollIntoView()}
function removeStoredItem(i){const c=getStoredCart();c.splice(i,1);setStoredCart(c);renderMiniCart();renderCartPage();if(!c.length)setTimeout(closeSheet,700)}
function clearCart(){setStoredCart([]);renderMiniCart();renderCartPage();if(window.bundleEl)bundleEl.classList.remove('show');closeSheet()}
function cartItemsHTML(cart){if(!cart.length)return'<div class="sheet-empty"><div class="sheet-empty-icon">🛒</div><p>Cart is empty.<br>Add services above.</p></div>';const social=cart.filter(i=>i.type!=='agency');const agency=cart.filter(i=>i.type==='agency');let html='';if(social.length){if(agency.length)html+='<div class="cart-section-head">Social Growth</div>';html+=social.map(i=>{const k=cart.indexOf(i);return`<div class="sheet-item"><div class="sheet-item-logo"><img src="${platLogo(i.platform)}" style="width:100%;height:100%"></div><div class="sheet-item-info"><strong>${serviceIcons[i.service]||''} ${i.service}</strong><span class="sheet-meta">${i.platform} · ${i.quantity} · ${i.delivery}</span>${i.url?`<span class="sheet-url">🔗 ${i.url.length>30?i.url.slice(0,30)+'…':i.url}</span>`:''}</div><div class="sheet-item-right"><strong class="sheet-price">${euro(i.price)}</strong><span class="sheet-remove" onclick="removeStoredItem(${k})">✕</span></div></div>`}).join('')}if(agency.length){if(social.length)html+='<div class="cart-section-head">Agency Services</div>';html+=agency.map(i=>{const k=cart.indexOf(i);return`<div class="sheet-item"><div class="sheet-item-logo" style="background:rgba(192,132,252,.12);border:1px solid rgba(192,132,252,.2);border-radius:10px;display:grid;place-items:center"><span style="font-size:16px">📋</span></div><div class="sheet-item-info"><strong>${i.service}</strong><span class="sheet-meta">Agency · Quote-based</span></div><div class="sheet-item-right"><strong class="sheet-price" style="color:#d8b4fe">Quote</strong><span class="sheet-remove" onclick="removeStoredItem(${k})">✕</span></div></div>`}).join('')}return html}
function renderMiniCart(){const cart=getStoredCart();const ci=document.getElementById('cartItems');const ct=document.getElementById('cartTotal');if(ci)ci.innerHTML=cartItemsHTML(cart);if(ct)ct.textContent=cart.length?cartTotalText(cart):'0€';const cpc=document.getElementById('cartPanelCount');if(cpc)cpc.textContent=cart.length?`${cart.length} item${cart.length>1?'s':''}  ·  ${cartTotalText(cart)}`:'Empty';renderSheetCart();updateCartCount()}
function renderSheetCart(){const si=document.getElementById('sheetItems');const st=document.getElementById('sheetTotal');if(!si)return;const cart=getStoredCart();si.innerHTML=cartItemsHTML(cart);if(st)st.textContent=cart.length?cartTotalText(cart):'0€'}
function openSheet(){if(window.innerWidth>760)return;renderSheetCart();document.getElementById('cartSheet')?.classList.add('open');document.getElementById('sheetBg')?.classList.add('open');document.body.style.overflow='hidden'}
function closeSheet(){document.getElementById('cartSheet')?.classList.remove('open');document.getElementById('sheetBg')?.classList.remove('open');document.body.style.overflow=''}
function cartTotalText(cart){const n=cart.filter(i=>typeof i.price==='number').reduce((s,i)=>s+i.price,0);const q=cart.some(i=>typeof i.price!=='number');return n+'€'+(q?' + quote':'')}
function socialMessage(cart=getStoredCart()){if(!cart.length&&document.getElementById('platformTiles'))cart=[getCurrent()];if(!cart.length)return'Hi LocaBey, I need help choosing a service.';const social=cart.filter(i=>i.type!=='agency');const agency=cart.filter(i=>i.type==='agency');let msg='Hi LocaBey,\n\n';if(social.length){msg+=`Social Growth order:\n${social.map((i,k)=>`${k+1}. ${i.platform} ${i.service} — ${i.quantity} — ${i.delivery} — URL: ${i.url||'Not added'} — Price: ${euro(i.price)}`).join('\n')}\n\n`}if(agency.length){msg+=`Agency services inquiry:\n${agency.map((i,k)=>`${k+1}. ${i.service}`).join('\n')}\n\nMy business:\nMy goal:\nTimeline:\nBudget range:\n\n`}msg+=`Estimated total: ${cartTotalText(cart)}\nPlease confirm price and payment.`;return msg}
function openWhatsApp(){openWhatsAppMessage(socialMessage())}
function requestAgency(service='Agency Services'){openWhatsAppMessage(`Hi LocaBey, I would like a quote for: ${service}.\n\nMy business:\nMy goal:\nTimeline:\nBudget range:`)}
function renderAll(){renderPlatforms();renderServices();renderQuantities();updateSummary()}function renderCartPage(){const target=document.getElementById('cartPageItems');if(!target)return;const cart=getStoredCart();target.innerHTML=cartItemsHTML(cart);const tot=document.getElementById('cartPageTotal');if(tot)tot.textContent=cart.length?cartTotalText(cart):'0€';const cnt=document.getElementById('cartPageCount');if(cnt)cnt.textContent=cart.length?`${cart.length} item${cart.length>1?'s':''}  ·  ${cartTotalText(cart)}`:'Empty'}
function initAnimations(){const o=new IntersectionObserver((entries)=>{entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');o.unobserve(e.target)}})},{threshold:0.12});document.querySelectorAll('.fade-up,.fade-scale').forEach(el=>o.observe(el))}
function addToAgencyCart(service,btn){const cart=getStoredCart();const idx=cart.findIndex(i=>i.type==='agency'&&i.service===service);if(idx>-1){cart.splice(idx,1);setStoredCart(cart);if(btn){btn.innerHTML='Add to inquiry <span>+</span>';btn.classList.remove('added')}}else{cart.push({type:'agency',service,price:'Quote'});setStoredCart(cart);if(btn){btn.innerHTML='Added ✓ <span>✓</span>';btn.classList.add('added')}}renderMiniCart()}
function initCatTabs(){const tabs=document.querySelectorAll('.cat-tab');if(!tabs.length)return;tabs.forEach(tab=>{tab.addEventListener('click',()=>{tabs.forEach(t=>t.classList.remove('active'));document.querySelectorAll('.cat-panel').forEach(p=>p.classList.remove('active'));tab.classList.add('active');document.querySelector(`.cat-panel[data-panel="${tab.dataset.cat}"]`)?.classList.add('active')})});document.querySelectorAll('.cat-panel').forEach(panel=>{const cards=panel.querySelectorAll('.service');const total=cards.length;cards.forEach((card,i)=>{const n=document.createElement('span');n.className='svc-num';n.textContent=`${i+1}/${total}`;card.prepend(n);const mc=card.querySelector('.mini-cta');if(!mc)return;const svc=mc.getAttribute('onclick')?.match(/requestAgency\('([^']+)'\)/)?.[1]||'';const btn=document.createElement('button');btn.className='agency-add-btn';const inCart=getStoredCart().some(c=>c.type==='agency'&&c.service===svc);btn.innerHTML=inCart?'Added ✓ <span>✓</span>':'Add to inquiry <span>+</span>';if(inCart)btn.classList.add('added');btn.addEventListener('click',()=>addToAgencyCart(svc,btn))mc.replaceWith(btn)})})}
document.addEventListener('DOMContentLoaded',()=>{injectShell();initBuilder();renderCartPage();initAnimations();initCatTabs()});
