const WHATSAPP_NUMBER = '33603939226';
const INSTAGRAM_URL = 'https://instagram.com/locabey.official';
const EMAIL = 'contact@locabey.com';

function toggleContact(){document.querySelector('.contact-wrap')?.classList.toggle('open');document.querySelector('.nav')?.classList.remove('mobile-open')}
function toggleMobileNav(e){e?.stopPropagation();document.querySelector('.nav')?.classList.toggle('mobile-open');document.querySelector('.contact-wrap')?.classList.remove('open')}
document.addEventListener('click',e=>{const w=document.querySelector('.contact-wrap');if(w&&!w.contains(e.target))w.classList.remove('open');const n=document.querySelector('.nav');if(n&&!n.contains(e.target))n.classList.remove('mobile-open')})

function getStoredCart(){try{return JSON.parse(localStorage.getItem('locabeyCart')||'[]')}catch{return[]}}
function setStoredCart(cart){localStorage.setItem('locabeyCart',JSON.stringify(cart));updateCartCount()}
function updateCartCount(){document.querySelectorAll('[data-cart-count]').forEach(el=>el.textContent=getStoredCart().length)}
function openWhatsAppMessage(message){window.open(`https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(message)}`,'_blank')}
function openInstagram(){window.open(INSTAGRAM_URL,'_blank')}
function openEmail(subject='LocaBey request',body='Hi LocaBey, I would like to discuss a project.'){window.location.href=`mailto:${EMAIL}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`}
function nav(){return `
<nav class="nav"><div class="wrap nav-inner"><a class="brand" href="index.html"><div class="logo">LB</div>LocaBey</a><div class="links"><a href="index.html">Home</a><a href="social-growth.html">Social Growth</a><a href="agency.html">Agency Services</a></div><div class="nav-actions"><button class="btn ghost mobile-menu-btn" onclick="toggleMobileNav(event)">Menu</button><a class="btn ghost nav-cart-btn" href="cart.html">🛒 Cart <span class="cart-count" data-cart-count>0</span></a><div class="contact-wrap"><button class="btn white" onclick="toggleContact()">Contact</button><div class="contact-menu"><a href="javascript:void(0)" onclick="openWhatsAppMessage('Hi LocaBey, I need help choosing the right service.')">WhatsApp</a><a href="javascript:void(0)" onclick="openInstagram()">Instagram DM</a><a href="javascript:void(0)" onclick="openEmail()">Email</a></div></div></div></div></nav>`}
function footer(){return `<footer><div class="wrap footer-inner"><strong style="color:white">LocaBey</strong><span><a href="index.html">Home</a> · <a href="social-growth.html">Social Growth</a> · <a href="agency.html">Agency Services</a> · <a href="cart.html">Cart</a> · Contact · Terms · Privacy</span><span>© 2026 LocaBey · Paris</span></div></footer>`}
function injectShell(){document.body.insertAdjacentHTML('afterbegin',nav());document.body.insertAdjacentHTML('beforeend',footer());updateCartCount()}

const catalog={
Instagram:{icon:'📸',services:{Followers:{'100':5,'500':10,'1,000':15,'5,000':40,'10,000':75,Custom:'Custom'},Likes:{'100':3,'500':7,'1,000':10,'5,000':35,'10,000':60,Custom:'Custom'},Views:{'100':1,'500':3,'1,000':5,'5,000':15,'10,000':25,Custom:'Custom'},Comments:{'100':10,'500':30,'1,000':50,Custom:'Custom'},Saves:{'100':5,'500':12,'1,000':20,'5,000':60,Custom:'Custom'},'Story Views':{'100':2,'500':5,'1,000':9,'5,000':20,Custom:'Custom'}}},
TikTok:{icon:'🎵',services:{Followers:{'100':5,'500':15,'1,000':25,'5,000':60,'10,000':100,Custom:'Custom'},Likes:{'100':3,'500':7,'1,000':15,'5,000':35,'10,000':70,Custom:'Custom'},Views:{'100':1,'500':3,'1,000':5,'5,000':15,'10,000':25,Custom:'Custom'},Comments:{'100':10,'500':25,'1,000':45,Custom:'Custom'},Reposts:{'100':5,'500':15,'1,000':25,Custom:'Custom'},Favorites:{'100':5,'500':15,'1,000':25,Custom:'Custom'}}},
YouTube:{icon:'▶️',services:{Subscribers:{'100':10,'500':40,'1,000':70,'5,000':200,Custom:'Custom'},Views:{'100':2,'500':5,'1,000':10,'5,000':25,'10,000':45,Custom:'Custom'},'Watch Hours':{'100h':20,'500h':60,'1,000h':100,'4,000h':300,Custom:'Custom'},Likes:{'100':5,'500':10,'1,000':20,Custom:'Custom'}}},
Facebook:{icon:'📘',services:{'Page Likes':{'100':2,'500':10,'1,000':15,'5,000':60,'10,000':100,Custom:'Custom'},Followers:{'100':3,'500':15,'1,000':20,'5,000':75,Custom:'Custom'},'Post Likes':{'100':1,'500':5,'1,000':10,'5,000':40,Custom:'Custom'}}},
'X / Twitter':{icon:'𝕏',services:{Followers:{'100':15,'500':75,'1,000':150,'5,000':500,Custom:'Custom'},Likes:{'100':10,'500':50,'1,000':100,'5,000':400,Custom:'Custom'},Reposts:{Custom:'Custom'},Views:{Custom:'Custom'}}},
Spotify:{icon:'🎧',services:{Plays:{'100':2,'500':5,'1,000':10,'5,000':25,'10,000':45,Custom:'Custom'},Followers:{'100':7,'500':15,'1,000':25,'5,000':70,Custom:'Custom'},'Monthly Listeners':{'100':10,'500':20,'1,000':40,'5,000':100,Custom:'Custom'},'Playlist Adds':{'100':8,'500':18,'1,000':35,Custom:'Custom'}}},
Snapchat:{icon:'👻',services:{Followers:{Custom:'Custom'},'Story Views':{Custom:'Custom'},Subscriptions:{Custom:'Custom'},'Profile Views':{Custom:'Custom'}}},Twitch:{icon:'🟣',services:{Followers:{Custom:'Custom'},'Channel Views':{Custom:'Custom'},'Live Viewers':{Custom:'Custom'},'Clip Views':{Custom:'Custom'}}},Telegram:{icon:'✈️',services:{'Channel Members':{Custom:'Custom'},'Post Views':{Custom:'Custom'},Reactions:{Custom:'Custom'},Comments:{Custom:'Custom'}}}
};
const bundleMap={Instagram:['Likes','Views','Saves','Story Views'],TikTok:['Likes','Views','Reposts','Favorites'],YouTube:['Views','Likes','Watch Hours','Subscribers'],Facebook:['Post Likes','Followers','Page Likes'],'X / Twitter':['Likes','Reposts','Views'],Spotify:['Plays','Monthly Listeners','Playlist Adds'],Snapchat:['Story Views','Profile Views'],Twitch:['Channel Views','Clip Views','Live Viewers'],Telegram:['Post Views','Reactions','Comments']};
let selectedPlatform='Instagram',selectedService='Followers',selectedQuantity='1,000',selectedDelivery='Immediate 24h',customMode=false;
function euro(v){return typeof v==='number'?v+'€':v}function priceObject(){return catalog[selectedPlatform].services[selectedService]}function getPrice(){if(customMode)return'Custom';return priceObject()[selectedQuantity]??'Custom'}
function perUnit(price,qty){if(typeof price!=='number')return'';const n=parseInt(String(qty).replace(/,/g,'').replace('h',''));if(!n||String(qty).includes('h'))return'';return(price/(n/1000)).toFixed(1).replace('.0','')+'€ / 1K'}
function badge(q,p){if(typeof p!=='number')return'';const n=parseInt(String(q).replace(/,/g,''));if(n>=5000)return'<span class="badge">Best value</span>';if(n>=1000)return'<span class="badge">Popular</span>';return''}
function initBuilder(){if(!document.getElementById('platformTiles'))return;window.platformTiles=document.getElementById('platformTiles');window.serviceTiles=document.getElementById('serviceTiles');window.quantityGrid=document.getElementById('quantityGrid');window.customQty=document.getElementById('customQty');window.urlEl=document.getElementById('url');window.bundleEl=document.getElementById('bundle');window.bundleOptionsEl=document.getElementById('bundleOptions');window.cartItemsEl=document.getElementById('cartItems');window.cartTotalEl=document.getElementById('cartTotal');urlEl.addEventListener('input',updateSummary);const deliveryCustomInput=document.getElementById('deliveryCustomInput');if(deliveryCustomInput)deliveryCustomInput.addEventListener('input',updateSummary);customQty.addEventListener('input',()=>{selectQuantity('Custom');});renderAll();renderMiniCart()}
function renderPlatforms(){platformTiles.innerHTML=Object.keys(catalog).map(p=>`<div class="tile ${p===selectedPlatform?'active':''}" onclick="selectPlatform('${p.replace(/'/g,"\\'")}')"><span class="icon">${catalog[p].icon}</span><strong>${p}</strong></div>`).join('')}
function renderServices(){const services=Object.keys(catalog[selectedPlatform].services);if(!services.includes(selectedService))selectedService=services[0];serviceTiles.innerHTML=services.map(s=>`<div class="service-tile ${s===selectedService?'active':''}" onclick="selectService('${s.replace(/'/g,"\\'")}')"><strong>${s}</strong><span class="service-options">${Object.keys(catalog[selectedPlatform].services[s]).length} options</span></div>`).join('')}
function renderQuantities(){const prices=priceObject();if(!prices[selectedQuantity])selectedQuantity=Object.keys(prices)[0];document.getElementById('priceGuideTitle').textContent=`${selectedPlatform} ${selectedService} pricing`;quantityGrid.innerHTML=Object.entries(prices).filter(([q])=>q!=='Custom').map(([q,p])=>`<div class="qty-tile ${!customMode&&q===selectedQuantity?'active':''}" onclick="selectQuantity('${q}')"><strong>${q}</strong><span class="price">${euro(p)}</span><span class="per">${perUnit(p,q)}</span>${badge(q,p)}</div>`).join('');if(prices.Custom){quantityGrid.innerHTML+=`<div class="qty-tile ${customMode?'active':''}" onclick="selectQuantity('Custom')"><strong>Custom</strong></div>`}const customQtyRow=document.getElementById('customQtyRow');if(customQtyRow)customQtyRow.style.display=customMode?'block':'none';updateSummary()}
function selectPlatform(p){selectedPlatform=p;selectedService=Object.keys(catalog[p].services)[0];selectedQuantity=Object.keys(catalog[p].services[selectedService])[0];customMode=false;renderAll()}function selectService(s){selectedService=s;selectedQuantity=Object.keys(catalog[selectedPlatform].services[s])[0];customMode=false;renderAll()}function selectQuantity(q){if(q==='Custom'){customMode=true;selectedQuantity=customQty.value?customQty.value+' custom':'Custom'}else{customMode=false;selectedQuantity=q}renderQuantities()}function selectDelivery(d,el){selectedDelivery=d;document.querySelectorAll('.delivery-tile').forEach(t=>t.classList.remove('active'));el.classList.add('active');const row=document.getElementById('deliveryCustomRow');if(row)row.style.display=d==='Custom'?'block':'none';updateSummary()}function dismissBundle(){if(window.bundleEl)bundleEl.classList.remove('show')}
function getCurrent(){const deliveryCustomEl=document.getElementById('deliveryCustomInput');const delivery=selectedDelivery==='Custom'&&deliveryCustomEl?.value.trim()?'Custom: '+deliveryCustomEl.value.trim():selectedDelivery;return{type:'social-growth',platform:selectedPlatform,service:selectedService,quantity:selectedQuantity,delivery,url:urlEl?.value.trim()||'',price:getPrice()}}function updateSummary(){if(!document.getElementById('sumPlatform'))return;const i=getCurrent();sumPlatform.textContent=i.platform;sumService.textContent=i.service;sumQuantity.textContent=i.quantity;sumDelivery.textContent=i.delivery;sumUrl.textContent=i.url?'Added':'Missing';sumPrice.textContent=euro(i.price)}
function addToCart(){const cart=getStoredCart();cart.push(getCurrent());setStoredCart(cart);renderMiniCart();showBundle(selectedPlatform,selectedService)}function showBundle(p,current){const sug=(bundleMap[p]||[]).filter(s=>s!==current&&catalog[p].services[s]);bundleOptionsEl.innerHTML=sug.map(s=>`<span class="pill" onclick="prefillAddon('${p}','${s}')">Add ${p} ${s}</span>`).join('');bundleEl.classList.add('show')}function prefillAddon(p,s){selectedPlatform=p;selectedService=s;selectedQuantity=Object.keys(catalog[p].services[s])[0];customMode=false;urlEl.value=getStoredCart().at(-1)?.url||urlEl.value;renderAll();document.getElementById('builder').scrollIntoView()}
function removeStoredItem(i){const c=getStoredCart();c.splice(i,1);setStoredCart(c);renderMiniCart();renderCartPage()}function clearCart(){setStoredCart([]);renderMiniCart();renderCartPage();if(window.bundleEl)bundleEl.classList.remove('show')}
function renderMiniCart(){if(!window.cartItemsEl)return;const cart=getStoredCart();if(!cart.length){cartItemsEl.innerHTML='<p class="note">No items yet.</p>';cartTotalEl.textContent='0€';return}cartItemsEl.innerHTML=cart.slice(-4).map((i,idx)=>`<div class="cart-item"><div><strong>${i.platform} ${i.service}</strong><br>${i.quantity} · ${i.delivery} · ${euro(i.price)}</div><div class="remove" onclick="removeStoredItem(${getStoredCart().length-cart.slice(-4).length+idx})">Remove</div></div>`).join('');cartTotalEl.textContent=cartTotalText(cart)}
function cartTotalText(cart){const n=cart.filter(i=>typeof i.price==='number').reduce((s,i)=>s+i.price,0);const q=cart.some(i=>typeof i.price!=='number');return n+'€'+(q?' + quote':'')}
function socialMessage(cart=getStoredCart()){if(!cart.length&&document.getElementById('platformTiles'))cart=[getCurrent()];if(!cart.length)return'Hi LocaBey, I need help choosing a service.';let lines=cart.map((i,k)=>`${k+1}. ${i.platform} ${i.service} — ${i.quantity} — ${i.delivery} — URL: ${i.url||'Not added'} — Price: ${euro(i.price)}`).join('\n');return`Hi LocaBey, I want to order:\n\n${lines}\n\nEstimated total: ${cartTotalText(cart)}\nPlease confirm price and payment.`}
function openWhatsApp(){openWhatsAppMessage(socialMessage())}
function requestAgency(service='Agency Services'){openWhatsAppMessage(`Hi LocaBey, I would like a quote for: ${service}.\n\nMy business:\nMy goal:\nTimeline:\nBudget range:`)}
function renderAll(){renderPlatforms();renderServices();renderQuantities();updateSummary()}function renderCartPage(){const target=document.getElementById('cartPageItems');if(!target)return;const cart=getStoredCart();if(!cart.length){target.innerHTML='<div class="empty">Your cart is empty. Add Social Growth services or request an Agency quote.</div>';document.getElementById('cartPageTotal').textContent='0€';return}target.innerHTML=cart.map((i,k)=>`<div class="cart-item"><div><strong>${i.platform} ${i.service}</strong><br>${i.quantity} · ${i.delivery}<br><span class="note">URL: ${i.url||'Not added'}</span></div><div><strong>${euro(i.price)}</strong><br><span class="remove" onclick="removeStoredItem(${k})">Remove</span></div></div>`).join('');document.getElementById('cartPageTotal').textContent=cartTotalText(cart)}
document.addEventListener('DOMContentLoaded',()=>{injectShell();initBuilder();renderCartPage()});
