const WHATSAPP_NUMBER = '33603939226';
const INSTAGRAM_URL = 'https://instagram.com/locabey.official';
const EMAIL = 'contact@locabey.com';
const B=(()=>{const pts=location.pathname.split('/').filter(Boolean);return pts.length>1?'../'.repeat(pts.length-1):''})();

function toggleContact(){document.querySelector('.contact-wrap')?.classList.toggle('open');document.querySelector('.nav')?.classList.remove('mobile-open')}
function toggleMobileNav(e){e?.stopPropagation();document.querySelector('.nav')?.classList.toggle('mobile-open');document.querySelector('.contact-wrap')?.classList.remove('open')}
document.addEventListener('click',e=>{const w=document.querySelector('.contact-wrap');if(w&&!w.contains(e.target))w.classList.remove('open');const n=document.querySelector('.nav');if(n&&!n.contains(e.target))n.classList.remove('mobile-open')})

function getStoredCart(){try{return JSON.parse(localStorage.getItem('locabeyCart')||'[]')}catch{return[]}}
function setStoredCart(cart){localStorage.setItem('locabeyCart',JSON.stringify(cart));updateCartCount()}
function navCartClick(e){if(window.innerWidth<=760){e.preventDefault();openSheet()}}
function updateCartCount(){const cart=getStoredCart();document.querySelectorAll('[data-cart-count]').forEach(el=>el.textContent=cart.length||'');const tot=cart.length?cartTotalText(cart):'';document.querySelectorAll('[data-cart-total]').forEach(el=>el.textContent=tot)}
function openWhatsAppMessage(message){window.open(`https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(message)}`,'_blank')}
function openInstagram(){window.open(INSTAGRAM_URL,'_blank','noopener,noreferrer')}
function openEmail(subject='LocaBey request',body='Hi LocaBey, I would like to discuss a project.'){window.location.href=`mailto:${EMAIL}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`}
function nav(){return `<nav class="nav"><div class="wrap nav-inner"><a class="brand" href="${B}index.html" aria-label="LocaBey home"><span class="logo"><svg viewBox="0 0 48 48" width="42" height="42" aria-hidden="true" focusable="false"><defs><linearGradient id="lbg" x1="0" y1="48" x2="48" y2="0" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="#5eead4"/><stop offset=".35" stop-color="#22d3ee"/><stop offset=".68" stop-color="#a78bfa"/><stop offset="1" stop-color="#ff6fa5"/></linearGradient></defs><rect width="48" height="48" rx="12" fill="url(#lbg)"/><rect x=".9" y=".9" width="46.2" height="46.2" rx="11.2" fill="none" stroke="#fff" stroke-opacity=".22"/><path d="M11 32 L20 23 L27 28 L37 15.5" fill="none" stroke="#fff" stroke-width="3.6" stroke-linecap="round" stroke-linejoin="round"/><path d="M30 15.5 L37 15.5 L37 22.5" fill="none" stroke="#fff" stroke-width="3.6" stroke-linecap="round" stroke-linejoin="round"/><circle cx="11" cy="32" r="2.4" fill="#fff"/></svg></span><span class="brand-name">Loca<span class="gradient-word">Bey</span></span></a><div class="links"><a href="${B}index.html">Home</a><a href="${B}social-growth.html">Social Growth</a><a href="${B}agency.html">Agency Services</a><a href="${B}blog/">Blog</a></div><div class="nav-actions"><button class="btn ghost mobile-menu-btn" onclick="toggleMobileNav(event)">Menu</button><a class="btn ghost nav-cart-btn" href="${B}cart.html" onclick="navCartClick(event)">🛒<span class="cart-label"> Cart </span><span class="cart-count" data-cart-count></span><span class="cart-nav-total" data-cart-total></span></a><div class="contact-wrap"><button class="btn white" onclick="toggleContact()">Contact</button><div class="contact-menu"><a href="https://wa.me/33603939226?text=Hi%20LocaBey%2C%20I%20need%20help%20choosing%20the%20right%20service." target="_blank" rel="noopener noreferrer">WhatsApp</a><a href="https://instagram.com/locabey.official" target="_blank" rel="noopener noreferrer">Instagram DM</a><a href="mailto:contact@locabey.com">Email</a></div></div></div></div></nav>`}
function footer(){return`<footer><div class="wrap footer-inner"><strong class="footer-name">LocaBey</strong><span class="footer-tagline">Your business builder, one-stop shop.</span><div class="footer-legal"><a href="${B}terms.html">Terms</a><a href="${B}privacy.html">Privacy</a><a href="${B}faq.html">FAQ</a></div><span class="footer-copy">© 2026 LocaBey · Paris</span></div></footer>`}
function cartSheetHTML(){return`<div class="sheet-bg" id="sheetBg" onclick="closeSheet()"></div><div class="cart-sheet" id="cartSheet"><div class="sheet-handle"></div><div class="sheet-header"><h2>Your Cart</h2><button class="sheet-close" onclick="closeSheet()">×</button></div><div class="sheet-items" id="sheetItems"></div><div class="sheet-footer"><div class="sheet-total-row"><span>Total</span><strong id="sheetTotal">0€</strong></div><p class="note sheet-note">No password needed. Confirmed before payment.</p><button class="btn green" style="width:100%;margin-top:12px;min-height:48px" onclick="openWhatsApp();closeSheet()">Send order on WhatsApp ↗</button><button class="btn muted-btn" style="width:100%;margin-top:8px;min-height:42px" onclick="clearCart()">Clear cart</button></div></div>`}
function injectShell(){const placeholder=document.querySelector('.nav-placeholder');if(placeholder){placeholder.outerHTML=nav()}else{document.body.insertAdjacentHTML('afterbegin',nav())}document.body.insertAdjacentHTML('beforeend',footer());if(!document.getElementById('cartSheet'))document.body.insertAdjacentHTML('beforeend',cartSheetHTML());updateCartCount()}

const serviceIcons={Followers:'👥',Subscribers:'👥','Channel Members':'👥',Likes:'❤️','Post Likes':'❤️','Page Likes':'👍',Comments:'💬',Reactions:'💬',Views:'👁','Channel Views':'👁','Post Views':'👁','Clip Views':'👁','Live Viewers':'👁',Saves:'🔖',Shares:'➤',Reposts:'🔁',Favorites:'⭐',Plays:'▶',Subscriptions:'🔔','Profile Views':'👤','Watch Hours':'⏱','Monthly Listeners':'🎧','Playlist Adds':'➕'};
const platLogos={Instagram:'instagram',TikTok:'tiktok',YouTube:'youtube',Facebook:'facebook','X / Twitter':'twitter',Spotify:'spotify',Snapchat:'snapchat',Twitch:'twitch',Telegram:'telegram'};
function platLogo(p){return`${B}logos/${platLogos[p]||p.toLowerCase()}.svg`}
function euro(v){return typeof v==='number'?v+'€':v}

function removeStoredItem(i){const c=getStoredCart();c.splice(i,1);setStoredCart(c);renderMiniCart();renderCartPage();if(!c.length)setTimeout(closeSheet,700)}
function clearCart(){setStoredCart([]);renderMiniCart();renderCartPage();if(window.bundleEl)bundleEl.classList.remove('show');closeSheet()}
function cartItemsHTML(cart){if(!cart.length)return'<div class="sheet-empty"><div class="sheet-empty-icon">🛒</div><p>Cart is empty.<br>Add services above.</p></div>';const social=cart.filter(i=>i.type!=='agency');const agency=cart.filter(i=>i.type==='agency');let html='';if(social.length){if(agency.length)html+='<div class="cart-section-head">Social Growth</div>';html+=social.map(i=>{const k=cart.indexOf(i);return`<div class="sheet-item"><div class="sheet-item-logo"><img src="${platLogo(i.platform)}" alt="${i.platform}" style="width:100%;height:100%"></div><div class="sheet-item-info"><strong>${serviceIcons[i.service]||''} ${i.service}</strong><span class="sheet-meta">${i.platform} · ${i.quantity} · ${i.delivery}</span>${i.url?`<span class="sheet-url">🔗 ${i.url.length>30?i.url.slice(0,30)+'…':i.url}</span>`:''}</div><div class="sheet-item-right"><strong class="sheet-price">${euro(i.price)}</strong><span class="sheet-remove" onclick="removeStoredItem(${k})">✕</span></div></div>`}).join('')}if(agency.length){if(social.length)html+='<div class="cart-section-head">Agency Services</div>';html+=agency.map(i=>{const k=cart.indexOf(i);return`<div class="sheet-item"><div class="sheet-item-logo" style="background:rgba(255,111,165,.12);border:1px solid rgba(255,111,165,.2);border-radius:10px;display:grid;place-items:center"><span style="font-size:16px">📋</span></div><div class="sheet-item-info"><strong>${i.service}</strong><span class="sheet-meta">Agency · Quote-based</span></div><div class="sheet-item-right"><strong class="sheet-price" style="color:#ffa8c8">Quote</strong><span class="sheet-remove" onclick="removeStoredItem(${k})">✕</span></div></div>`}).join('')}return html}
function updateCartBar(){const cart=getStoredCart();const bar=document.getElementById('cartBar');if(!bar)return;const txt=document.getElementById('cartBarText');if(cart.length){bar.classList.add('visible');if(txt)txt.textContent=`${cart.length} item${cart.length>1?'s':''} · ${cartTotalText(cart)}`}else{bar.classList.remove('visible')}}
function renderMiniCart(){const cart=getStoredCart();const ci=document.getElementById('cartItems');const ct=document.getElementById('cartTotal');if(ci)ci.innerHTML=cartItemsHTML(cart);if(ct)ct.textContent=cart.length?cartTotalText(cart):'0€';const cpc=document.getElementById('cartPanelCount');if(cpc)cpc.textContent=cart.length?`${cart.length} item${cart.length>1?'s':''}  ·  ${cartTotalText(cart)}`:'Empty';renderSheetCart();updateCartCount();syncAgencyButtons();updateCartBar();}
function renderSheetCart(){const si=document.getElementById('sheetItems');const st=document.getElementById('sheetTotal');if(!si)return;const cart=getStoredCart();si.innerHTML=cartItemsHTML(cart);if(st)st.textContent=cart.length?cartTotalText(cart):'0€'}
function openSheet(){if(window.innerWidth>760)return;renderSheetCart();document.getElementById('cartSheet')?.classList.add('open');document.getElementById('sheetBg')?.classList.add('open');document.body.style.overflow='hidden'}
function closeSheet(){document.getElementById('cartSheet')?.classList.remove('open');document.getElementById('sheetBg')?.classList.remove('open');document.body.style.overflow=''}
function cartTotalText(cart){const n=cart.filter(i=>typeof i.price==='number').reduce((s,i)=>s+i.price,0);const q=cart.some(i=>typeof i.price!=='number');return n+'€'+(q?' + quote':'')}
function socialMessage(cart=getStoredCart()){if(!cart.length&&document.getElementById('platformTiles')&&typeof getCurrent==='function')cart=[getCurrent()];if(!cart.length)return'Hi LocaBey, I need help choosing a service.';const social=cart.filter(i=>i.type!=='agency');const agency=cart.filter(i=>i.type==='agency');let msg='Hi LocaBey,\n\n';if(social.length){msg+=`Social Growth order:\n${social.map((i,k)=>`${k+1}. ${i.platform} ${i.service} — ${i.quantity} — ${i.delivery} — URL: ${i.url||'Not added'} — Price: ${euro(i.price)}`).join('\n')}\n\n`}if(agency.length){msg+=`Agency services inquiry:\n${agency.map((i,k)=>`${k+1}. ${i.service}`).join('\n')}\n\nMy business:\nMy goal:\nTimeline:\nBudget range:\n\n`}msg+=`Estimated total: ${cartTotalText(cart)}\nPlease confirm price and payment.`;return msg}
function openWhatsApp(){openWhatsAppMessage(socialMessage())}
function requestAgency(service='Agency Services'){openWhatsAppMessage(`Hi LocaBey, I would like a quote for: ${service}.\n\nMy business:\nMy goal:\nTimeline:\nBudget range:`)}
function renderCartPage(){const target=document.getElementById('cartPageItems');if(!target)return;const cart=getStoredCart();target.innerHTML=cartItemsHTML(cart);const tot=document.getElementById('cartPageTotal');if(tot)tot.textContent=cart.length?cartTotalText(cart):'0€';const cnt=document.getElementById('cartPageCount');if(cnt)cnt.textContent=cart.length?`${cart.length} item${cart.length>1?'s':''}  ·  ${cartTotalText(cart)}`:'Empty'}
function initAnimations(){const o=new IntersectionObserver((entries)=>{entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');o.unobserve(e.target)}})},{threshold:0.12});document.querySelectorAll('.fade-up,.fade-scale').forEach(el=>o.observe(el))}
function toggleAgencyCart(service,btn){const cart=getStoredCart();const idx=cart.findIndex(i=>i.type==='agency'&&i.service===service);if(idx>-1){cart.splice(idx,1);setStoredCart(cart);if(btn){btn.innerHTML='Request a quote <span>+</span>';btn.classList.remove('added');}}else{cart.push({type:'agency',service,price:'Quote'});setStoredCart(cart);if(btn){btn.innerHTML='Added ✓ <span>✓</span>';btn.classList.add('added');}}renderMiniCart();}
function syncAgencyButtons(){const cart=getStoredCart();document.querySelectorAll('.agency-add-btn[data-service]').forEach(function(btn){const svc=btn.dataset.service;const inCart=cart.some(i=>i.type==='agency'&&i.service===svc);btn.innerHTML=inCart?'Added ✓ <span>✓</span>':'Request a quote <span>+</span>';btn.classList.toggle('added',inCart);});}
function initCatTabs(){const tabs=document.querySelectorAll('.cat-tab');if(!tabs.length)return;tabs.forEach(tab=>{tab.addEventListener('click',()=>{tabs.forEach(t=>t.classList.remove('active'));document.querySelectorAll('.cat-panel').forEach(p=>p.classList.remove('active'));tab.classList.add('active');document.querySelector(`.cat-panel[data-panel="${tab.dataset.cat}"]`)?.classList.add('active')})});document.querySelectorAll('.cat-panel').forEach(panel=>{const cards=panel.querySelectorAll('.service');const total=cards.length;cards.forEach((card,i)=>{const n=document.createElement('span');n.className='svc-num';n.textContent=`${i+1}/${total}`;card.prepend(n);const mc=card.querySelector('.mini-cta');if(!mc)return;const svc=mc.getAttribute('onclick')?.match(/requestAgency\('([^']+)'\)/)?.[1]||'';const btn=document.createElement('button');btn.className='agency-add-btn';btn.dataset.service=svc;const inCart=getStoredCart().some(c=>c.type==='agency'&&c.service===svc);btn.innerHTML=inCart?'Added ✓ <span>✓</span>':'Request a quote <span>+</span>';if(inCart){btn.classList.add('added');}btn.addEventListener('click',function(){toggleAgencyCart(svc,btn);});mc.replaceWith(btn);})})}
document.addEventListener('DOMContentLoaded',()=>{injectShell();if(typeof initBuilder==='function')initBuilder();renderCartPage();initAnimations();initCatTabs()});
