const catalog={
Instagram:{icon:'<img src="logos/instagram.svg" class="plat-logo" alt="Instagram">',services:{Followers:{'100':5,'500':10,'1,000':15,'5,000':40,'10,000':75,Custom:'Custom'},Likes:{'100':3,'500':7,'1,000':10,'5,000':35,'10,000':60,Custom:'Custom'},Views:{'100':1,'500':3,'1,000':5,'5,000':15,'10,000':25,Custom:'Custom'},Comments:{'100':10,'500':30,'1,000':50,Custom:'Custom'},Saves:{'100':5,'500':12,'1,000':20,'5,000':60,Custom:'Custom'},Shares:{'100':2,'500':5,'1,000':9,'5,000':20,Custom:'Custom'}}},
TikTok:{icon:'<img src="logos/tiktok.svg" class="plat-logo" alt="TikTok">',services:{Followers:{'100':5,'500':15,'1,000':25,'5,000':60,'10,000':100,Custom:'Custom'},Likes:{'100':3,'500':7,'1,000':15,'5,000':35,'10,000':70,Custom:'Custom'},Views:{'100':1,'500':3,'1,000':5,'5,000':15,'10,000':25,Custom:'Custom'},Comments:{'100':10,'500':25,'1,000':45,Custom:'Custom'},Reposts:{'100':5,'500':15,'1,000':25,Custom:'Custom'},Favorites:{'100':5,'500':15,'1,000':25,Custom:'Custom'}}},
YouTube:{icon:'<img src="logos/youtube.svg" class="plat-logo" alt="YouTube">',services:{Subscribers:{'100':10,'500':40,'1,000':70,'5,000':200,Custom:'Custom'},Views:{'100':2,'500':5,'1,000':10,'5,000':25,'10,000':45,Custom:'Custom'},'Watch Hours':{'100h':20,'500h':60,'1,000h':100,'4,000h':300,Custom:'Custom'},Likes:{'100':5,'500':10,'1,000':20,Custom:'Custom'}}},
Facebook:{icon:'<img src="logos/facebook.svg" class="plat-logo" alt="Facebook">',services:{'Page Likes':{'100':2,'500':10,'1,000':15,'5,000':60,'10,000':100,Custom:'Custom'},Followers:{'100':3,'500':15,'1,000':20,'5,000':75,Custom:'Custom'},'Post Likes':{'100':1,'500':5,'1,000':10,'5,000':40,Custom:'Custom'}}},
'X / Twitter':{icon:'<img src="logos/twitter.svg" class="plat-logo" alt="X / Twitter">',services:{Followers:{'100':15,'500':75,'1,000':150,'5,000':500,Custom:'Custom'},Likes:{'100':10,'500':50,'1,000':100,'5,000':400,Custom:'Custom'},Reposts:{Custom:'Custom'},Views:{Custom:'Custom'}}},
Spotify:{icon:'<img src="logos/spotify.svg" class="plat-logo" alt="Spotify">',services:{Plays:{'100':2,'500':5,'1,000':10,'5,000':25,'10,000':45,Custom:'Custom'},Followers:{'100':7,'500':15,'1,000':25,'5,000':70,Custom:'Custom'},'Monthly Listeners':{'100':10,'500':20,'1,000':40,'5,000':100,Custom:'Custom'},'Playlist Adds':{'100':8,'500':18,'1,000':35,Custom:'Custom'}}},
Snapchat:{icon:'<img src="logos/snapchat.svg" class="plat-logo" alt="Snapchat">',services:{Followers:{Custom:'Custom'},Shares:{Custom:'Custom'},Subscriptions:{Custom:'Custom'},'Profile Views':{Custom:'Custom'}}},Twitch:{icon:'<img src="logos/twitch.svg" class="plat-logo" alt="Twitch">',services:{Followers:{Custom:'Custom'},'Channel Views':{Custom:'Custom'},'Live Viewers':{Custom:'Custom'},'Clip Views':{Custom:'Custom'}}},Telegram:{icon:'<img src="logos/telegram.svg" class="plat-logo" alt="Telegram">',services:{'Channel Members':{Custom:'Custom'},'Post Views':{Custom:'Custom'},Reactions:{Custom:'Custom'},Comments:{Custom:'Custom'}}}
};
const bundleMap={Instagram:['Likes','Views','Saves','Shares'],TikTok:['Likes','Views','Reposts','Favorites'],YouTube:['Views','Likes','Watch Hours','Subscribers'],Facebook:['Post Likes','Followers','Page Likes'],'X / Twitter':['Likes','Reposts','Views'],Spotify:['Plays','Monthly Listeners','Playlist Adds'],Snapchat:['Shares','Profile Views'],Twitch:['Channel Views','Clip Views','Live Viewers'],Telegram:['Post Views','Reactions','Comments']};
let selectedPlatform='Instagram',selectedService='Followers',selectedQuantity='1,000',selectedDelivery='Immediate 24h',customMode=false;
function priceObject(){return catalog[selectedPlatform].services[selectedService]}function getPrice(){if(customMode)return'Custom';return priceObject()[selectedQuantity]??'Custom'}
function perUnit(price,qty){if(typeof price!=='number')return'';const n=parseInt(String(qty).replace(/,/g,'').replace('h',''));if(!n||String(qty).includes('h'))return'';return(price/(n/1000)).toFixed(1).replace('.0','')+'€ / 1K'}
function badge(q,p){if(typeof p!=='number')return'';const n=parseInt(String(q).replace(/,/g,''));if(n>=5000)return'<span class="badge">Best value</span>';if(n>=1000)return'<span class="badge">Popular</span>';return''}
function initBuilder(){if(!document.getElementById('platformTiles'))return;const _p=new URLSearchParams(window.location.search);const _plat=_p.get('platform');const _svc=_p.get('service');if(_plat&&catalog[_plat]){selectedPlatform=_plat;const _svcs=Object.keys(catalog[_plat].services);selectedService=_svcs.includes(_svc)?_svc:_svcs[0];selectedQuantity=Object.keys(catalog[_plat].services[selectedService])[0];}window.platformTiles=document.getElementById('platformTiles');window.serviceTiles=document.getElementById('serviceTiles');window.quantityGrid=document.getElementById('quantityGrid');window.customQty=document.getElementById('customQty');window.urlEl=document.getElementById('url');window.bundleEl=document.getElementById('bundle');window.bundleOptionsEl=document.getElementById('bundleOptions');window.cartItemsEl=document.getElementById('cartItems');window.cartTotalEl=document.getElementById('cartTotal');urlEl.addEventListener('input',updateSummary);const deliveryCustomInput=document.getElementById('deliveryCustomInput');if(deliveryCustomInput)deliveryCustomInput.addEventListener('input',updateSummary);customQty.addEventListener('input',()=>{selectQuantity('Custom');});renderAll();renderMiniCart()}
function renderPlatforms(){platformTiles.innerHTML=Object.keys(catalog).map(p=>`<div class="tile ${p===selectedPlatform?'active':''}" onclick="selectPlatform('${p.replace(/'/g,"\\'")}')"><span class="icon">${catalog[p].icon}</span><strong>${p}</strong></div>`).join('')}
function renderServices(){const services=Object.keys(catalog[selectedPlatform].services);if(!services.includes(selectedService))selectedService=services[0];serviceTiles.innerHTML=services.map(s=>`<div class="service-tile ${s===selectedService?'active':''}" onclick="selectService('${s.replace(/'/g,"\\'")}')"><span class="s-icon">${serviceIcons[s]||''}</span><strong>${s}</strong></div>`).join('')}
function renderQuantities(){const prices=priceObject();if(!prices[selectedQuantity])selectedQuantity=Object.keys(prices)[0];document.getElementById('priceGuideTitle').textContent=`${selectedPlatform} ${selectedService} pricing`;quantityGrid.innerHTML=Object.entries(prices).filter(([q])=>q!=='Custom').map(([q,p])=>`<div class="qty-tile ${!customMode&&q===selectedQuantity?'active':''}" onclick="selectQuantity('${q}')"><strong>${q}</strong><span class="price">${euro(p)}</span><span class="per">${perUnit(p,q)}</span>${badge(q,p)}</div>`).join('');if(prices.Custom){quantityGrid.innerHTML+=`<div class="qty-tile ${customMode?'active':''}" onclick="selectQuantity('Custom')"><strong>Custom</strong></div>`}const customQtyRow=document.getElementById('customQtyRow');if(customQtyRow)customQtyRow.style.display=customMode?'block':'none';updateSummary()}
function selectPlatform(p){selectedPlatform=p;selectedService=Object.keys(catalog[p].services)[0];selectedQuantity=Object.keys(catalog[p].services[selectedService])[0];customMode=false;renderAll()}function selectService(s){selectedService=s;selectedQuantity=Object.keys(catalog[selectedPlatform].services[s])[0];customMode=false;renderAll()}function selectQuantity(q){if(q==='Custom'){customMode=true;selectedQuantity=customQty.value?customQty.value+' custom':'Custom'}else{customMode=false;selectedQuantity=q}renderQuantities()}function selectDelivery(d,el){selectedDelivery=d;document.querySelectorAll('.delivery-tile').forEach(t=>t.classList.remove('active'));el.classList.add('active');const row=document.getElementById('deliveryCustomRow');if(row)row.style.display=d==='Custom'?'block':'none';updateSummary()}function dismissBundle(){if(window.bundleEl)bundleEl.classList.remove('show')}
function getCurrent(){const deliveryCustomEl=document.getElementById('deliveryCustomInput');const delivery=selectedDelivery==='Custom'&&deliveryCustomEl?.value.trim()?'Custom: '+deliveryCustomEl.value.trim():selectedDelivery;return{type:'social-growth',platform:selectedPlatform,service:selectedService,quantity:selectedQuantity,delivery,url:urlEl?.value.trim()||'',price:getPrice()}}
function updateSummary(){if(!document.getElementById('sumPlatform'))return;const i=getCurrent();sumPlatform.textContent=i.platform;sumService.textContent=i.service;sumQuantity.textContent=i.quantity;sumDelivery.textContent=i.delivery;sumUrl.textContent=i.url?'Added':'Missing';sumPrice.textContent=euro(i.price);}
function addToCart(){const cart=getStoredCart();cart.push(getCurrent());setStoredCart(cart);renderMiniCart();showBundle(selectedPlatform,selectedService);const bar=document.getElementById('cartBar');if(bar){bar.classList.add('flash');setTimeout(()=>bar.classList.remove('flash'),550)}}function showBundle(p,current){const sug=(bundleMap[p]||[]).filter(s=>s!==current&&catalog[p].services[s]);bundleOptionsEl.innerHTML=sug.map(s=>`<span class="pill" onclick="prefillAddon('${p}','${s}')">Add ${p} ${s}</span>`).join('');bundleEl.classList.add('show')}function prefillAddon(p,s){selectedPlatform=p;selectedService=s;selectedQuantity=Object.keys(catalog[p].services[s])[0];customMode=false;urlEl.value=getStoredCart().at(-1)?.url||urlEl.value;renderAll();document.getElementById('builder').scrollIntoView()}
function renderAll(){renderPlatforms();renderServices();renderQuantities();updateSummary()}
